services:
    Asdoria\SyliusQuickShoppingPlugin\EventListener\ProductVariantEntitySubscriber:
        arguments:
            $productVariantHelper: '@Asdoria\SyliusQuickShoppingPlugin\Helper\ProductVariantHelper'
        tags:
            - { name: jms_serializer.event_subscriber }
